### ISSUE TITLE
How to provision a small collector

### ISSUE THREAD

**Issue by jamesla** [logicmonitor/logicmonitor-ansible#6]
I am trying to create a collector using this module with a size of small.

It appears to default to a medium and I can't find a property that allows me to change this to small.

Is this possible with this plugin?

**Comment by ethanculler** [comment]
Currently, it is unfortunately not possible. This module uses our RPC based API which pre-dates the collector sizing options. I'm not 100% sure where the updated version of the module is on the road map, however, I will forward this to the appropriate people to get it scheduled.

**Comment by jamesla** [comment]
Ok thanks Ethan
